#!/usr/bin/env python
# -*- coding: utf-8 -*-

import string
from django.utils.translation import ugettext_lazy as _

names = set(
    ["یکتا", "یک‌تا", "1ta", "yekta", "آبنوس", "abnous", "abnoos", "ابریشم", "abrisham", "عادل", "adel", "aadel",
     "افراسیاب", "afrasiab", "afrasyab", "افروز", "afrooz", "afrouz", "افروغ", "afrough", "afroogh", "افسانه",
     "afsaneh", "afsane", "افشان", "afshan", "افشار", "afshar", "افشین", "afshin", "آگرین", "agrin", "احمد", "ahmad",
     "آهو", "ahoo", "آیدین", "aidin", "aydin", "آیین‌گشسب", "آیین گشسب", "aiingoshasb", "aiingoshasb", "آیسا", "aisa",
     "aysa", "اژدر", "ajdar", "ajhadr", "اكبر", "akbar", "اخگر", "akhgar", "اختر", "akhtar", "aqtar", "اكرم", "akram",
     "آلاله", "alaleh", "alale", "البرز", "alborz", "علی", "ali", "علیرضا", "علی‌رضا", "alireza", "ali reza", "الوند",
     "alvand", "amal", "امش", "amash", "aamash", "آمنه", "ameneh", "amene", "امین", "amin", "امیر", "amin", "امیتیس",
     "amir", "عمار", "amitis", "امتیس", "ammar", "amar", "amaar", "ammaar", "اناهید", "amtis", "ametis", "آناهیتا",
     "anahid", "آندریا", "anahita", "آنوشا", "andria", "andrya", "انوشه", "anoosha", "anousha", "انوشیروان", "anoosheh",
     "anousheh", "انوش", "anooshirvan", "anushirvan", "انوشا", "anoush", "anoosh", "آراد", "anousha", "anoosha", "آراز",
     "araad", "arad", "ارخشا", "araaz", "araz", "آرش", "arakhsha", "ارشک", "arash", "اردلان", "arashk", "اردشیر",
     "ardalan", "اردوان", "ardashir", "ardesheer", "ardavan", "ardawan", "ارغوان", "arezoo", "arezou", "آریا",
     "arghavan", "arghawan", "آریان", "aria", "آریابان", "آرین", "ariaan", "arian", "آریادخت", "ariaban", "آریافر",
     "ariadokht", "آریامن", "ariafar", "آریامنش", "ariaman", "آریامهر", "آریا منش", "ariamanesh", "آرین", "آریا مهر",
     "ariamehr", "آریانا", "arian", "آریانوش", "ariana", "آرینا", "arianoush", "arianoosh", "آریو", "arina", "آریوبرزن",
     "ario", "ارژنگ", "ariobarzan", "ارمایل", "arjang", "arjhang", "آرمان", "armail", "armayl", "آرمین", "arman",
     "آرمینا", "armin", "آرمینه", "armina", "آرمیتا", "armineh", "اروشا", "armita", "ارسلان", "arousha", "aroosha",
     "آرشام", "arsalan", "ارشام", "arsham", "ارشیا", "arsham", "آرتا", "arshia", "arshya", "آرتان", "arta", "آرتین",
     "artan", "آرتمیس", "arteen", "artin", "ارتمیس", "artemis", "اروند", "artemis", "آروین", "arvand", "arwand", "آساد",
     "arvin", "اسدالله", "asad", "آسانا", "asadollah", "asadolah", "اصغر", "asana", "اشکان", "عسکر", "asghar", "asqar",
     "اشکبوس", "ashkan", "آسیه", "اشک‌بوس", "ashkboos", "ashkbus", "عسكر", "asiyeh", "asieh", "آستیاژ", "askae",
     "asqar", "آستیاگ", "astiaj", "astiajh", "آتنا", "astyag", "astiag", "آتوسا", "astyaj", "astiaj", "آترین", "atena",
     "آتورپات", "atoosa"]) | set(
    ["atousa", "آوید", "atousa", "atoosa", "آویده", "atrin", "آویژه", "atropat", "آوین", "avid", "آوینه", "avideh",
     "avide", "آویسا", "avijeh", "avijheh", "avizheh", "avije", "avijhe", "avizhe", "آیدا", "avin", "awin", "آیسان",
     "avineh", "avine", "آزاده", "avisa", "اعظم", "ayda", "aida", "آذر", "aysan", "aisan", "آذرافروز", "azade",
     "azadeh", "آذرخش", "azam", "a'zam", "آذرگون", "azar", "آذرمه", "azarafrouz", "azarafrooz", "آزرمگان", "azarakhsh",
     "آزرمیدخت", "azargoon", "azargoun", "آذرنوش", "azarmeh", "آذین", "آزرم‌گان", "azarmgan", "azarmgan",
     "azarmidokht", "بابک", "azarnoush", "azarnoosh", "باقر", "azeen", "azin", "بهارک", "aziz", "بهاران", "babak",
     "بهاره", "bagher", "baqer", "بهمن", "baharak", "بهمنش", "baharan", "بهرام", "bahareh", "bahare", "بامداد",
     "bahman", "بامین", "bahmansh", "behmanesh", "bahmanesh", "بامشاد", "bahram", "بنفشه", "bamdad", "بانو", "bamin",
     "باربد", "bamshad", "بردیا", "banafsheh", "banafshe", "برسام", "banoo", "banu", "برزن", "barbod", "barbad",
     "برزین", "bardia", "بایرام", "barsam", "به‌آیین", "barzan", "بهبد", "barzin", "بهداد", "bayram", "bairam", "بهدیس",
     "به آیین", "behaeen", "behayin", "بهدخت", "به‌بد", "behbod", "بهجت", "به‌بداد", "behdad", "بهنام", "behdis",
     "بهناز", "behdokht", "behjat", "bahjat", "بهراد", "behnam", "بهرنگ", "behnaz", "بهرخ", "بهروز", "behrad", "بهشاد",
     "behrang", "بهشید", "behrokh", "بهزاد", "behrooz", "behrouz", "بنیامین", "behshad", "بیژن", "behshid", "behsheed",
     "بیتا", "behzad", "برنا", "benyamin", "برزو", "bijan", "bijhan", "بزرگمهر", "bita", "برومند", "borna", "چکامه",
     "borzoo", "borzu", "چنگیز", "بزرگ‌مهر", "bozorgmehr", "چه‌کو", "broumand", "chakameh", "chakame",
     "chekameh", "chekame", "چیاکو", "changiz", "چومان", "chekoo", "chekou", "دادمهر", "chia", "دادویه", "chiakoo",
     "chiaku", "chiako", "دامون", "chooman", "chuman", "chouman", "دانو", "dadmehr", "دانوش", "dadooye", "dadouye",
     "daduye", "دارا", "damoon", "damun", "داراب", "danoo", "danu", "داریوش", "danoush", "danoosh", "دلارا", "dara",
     "دلارام", "darab", "دلکش", "daryoush", "darioosh", "دلسا", "دل‌آرا", "delara", "دلوسه", "دل‌آرام", "delaram",
     "دنا", "دل‌کش", "delkash", "delkesh", "دیاکو", "دل‌سا", "delsa", "دینا", "delvaseh", "delwaseh", "دوکا", "dena",
     "دُرنا", "diako", "diakoo", "دُرّی", "dina", "دومان", "dooka", "douka", "ابراهیم", "dorna", "احسان", "dorray",
     "douman", "dooman", "الهه", "ebrahim", "الهام", "ehsan", "ehsan", "الیاس", "ehteram", "عماد", "الاهه",
     "elahe", "elaheh", "عصام", "elham", "اسفندیار"]) | set(
    ["اسحاق", "elyas", "ilias", "اسکندر", "emad", "emaad", "اسماعیل", "esam", "esaam", "عصمت", "esfandiar", "esfandyar",
     "استر", "eshagh", "eshaq", "عزت", "eskanar", "iskanar", "فائزه", "اسمعیل", "esmaiil", "ismaiil", "فهام", "esmat",
     "فهیمه", "ester", "فه‌رهاد", "ezat", "azzat", "فاختک", "faeze", "faezeh", "فرح", "faham", "فرهناز", "fahime",
     "fahimeh", "فرخزاد", "فه راد", "fahrad", "fahrahad", "فرامرز", "fakhtak", "فرانک", "farah", "فربد", "farahnaz",
     "فرداد", "فرخ‌زاد", "farahzad", "فردین", "faramarz", "فرین", "faranak", "فرهاد", "farbod", "فرهام", "fardad",
     "فرهود", "fardin", "فریبا", "fareen", "farin", "faryn", "فریبرز", "farhad", "فریماه", "farham", "فریناز",
     "farhood", "farhud", "farhoud", "فرجام", "fariba", "فرناد", "fariborz", "فرنام", "فری‌ماه", "farimah", "farimah",
     "فرناز", "فری‌ناز", "farinaz", "farinaz", "farynaaz", "فرنیا", "farjam", "فرنوش", "farnad", "فرخ", "farnam",
     "فرسا", "farnaz", "فرشاد", "farnia", "فرشید", "farnoosh", "farnoush", "فرشیده", "farokh", "farrokh", "فرورتیش",
     "farsa", "فریا", "farshad", "فریما", "farshid", "فرزاد", "farshide", "farshideh", "فرزام", "farvartish",
     "farwartish", "فرزان", "farya", "faria", "فرزین", "faryma", "farima", "فاطمه", "farzad", "فتحیه", "farzam",
     "فتانه", "farzan", "فیروز", "farzin", "فیروزه", "fatemeh", "fateme", "فوزیه", "fathie", "fathieh", "فروزنده",
     "fattane", "fatane", "fattaneh", "fataneh", "فروغ", "firooz", "firuz", "pirouz", "pirooz", "piruz",
     "firouz", "firouzeh", "firouze", "firoozeh", "firooze", "firuze", "firuzeh", "فوژان", "foozieh", "foozie",
     "fouzie", "fouzieh", "fuzie", "fuzieh", "گرشاسب", "foroozande", "foroozandeh", "fruzande", "fruzandeh", "گَرسیوَز",
     "forough", "foroogh", "گشتاسب", "forouhar", "foroohar", "farvahar", "گلاره", "foujan", "foojan", "foojaan", "قدیر",
     "garshasb", "garshaseb", "gorshasb", "gorshaseb", "قاسم", "garsivaz", "garsious", "غلام", "gashtasb", "goshtaseb",
     "goshtasb", "gashtaseb", "گیلا", "gelare", "gelareh", "golare", "golareh", "گیلانه", "ghadir", "qadir", "گیلدا",
     "ghasem", "qasem", "گیسو", "gholam", "qolam", "گیتا", "gila", "gyla", "gilaneh", "gilane", "گیو", "gilda",
     "gylda", "gisoo", "ghisoe", "gisou", "گوهر", "gita", "guita", "گوهرشاد", "giti", "gity", "گلابتون", "giv",
     "giw", "گل‌افروز", "gjorban", "qorban", "gohar", "gowhar", "گلاوژ", "goharshad", "gowharshad", "گلبهار",
     "golabetoon", "golabetoun", "golabetun", "golabatoon", "golabatoun", "golabatun", "گلبانو", "golafrooz",
     "golafrouz", "golafruz", "گلبیز", "گل‌آوژ", "golawag", "golavaj", "golaavaj", "golawaj", "گلینوش", "گل‌بهار",
     "golbahaar", "golbahar", "گلمیس", "golbanu"]) | set(
    ["golbanoo", "گلنار", "گل‌بیز", "golbeaz", "golbiz", "golbeez", "golbyz", "گلناز", "goli", "گلنسا", "golinoush",
     "golinoosh", "golinush", "گلنوش", "گل‌میس", "golmis", "گلپا", "گل‌نار", "golnaar", "golnar", "گلپری", "گل‌ناز",
     "golnaz", "golnaaz", "گلپونه", "گل‌نسا", "golnesa", "گلرخ", "گل‌نوش", "golnoosh", "golnoush", "golnush", "گلرو",
     "golpa", "golpaa", "گلسا", "golpari", "golpary", "گلشن", "گل‌پونه", "golpooneh", "golpouneh", "golpuneh",
     "golpoone", "golpoune", "golpune", "گلشید", "گل‌رخ", "golrokh", "گلشیفته", "گل‌رو", "golroo", "golrou", "golru",
     "گلتاج", "گل‌سا", "golsa", "golsaa", "گلتن", "گل‌شن", "golshan", "گودرز", "گل‌شید", "golsheed", "golshid",
     "golshyd", "گردآفرید", "گل‌شیفته", "golsheefteh", "golshifteh", "golshyfteh", "golsheafteh", "golsheefte",
     "golshifte", "golshyfte", "golsheafte", "گرگین", "گل‌تاج", "goltaaj", "goltaj", "گستهم", "goltan", "گوران",
     "goodarz", "gudarz", "goudarz", "هادی", "گردافرید", "gordafarid", "gordafaryd", "gordaafarid", "حبیب", "gorgin",
     "حدیث", "gostham", "هاجر", "gouran", "gooran", "guran", "حامد", "haadi", "hadi", "hady", "haady", "حمید", "habib",
     "هامون", "hadis", "حمزه", "hajar", "haajar", "حنیف", "hamed", "haamed", "حنان", "hamid", "حسن", "hamoon", "hamoun",
     "haamoon", "haamoun", "haamun", "hamun", "هاشم", "hamze", "hamzeh", "هستی", "hanif", "حاتم", "hannan", "hanan",
     "هنگامه", "hasan", "حسام", "hashem", "hashim", "haashem", "haashim", "حیدر", "hasti", "هدا", "hatam", "haatam",
     "حجت", "hengame", "hengameh", "هما", "hesam", "همایون", "heydar", "heidar", "حمیرا", "هدی", "hoda", "هومان",
     "hojat", "hojjat", "هوروش", "homa", "هوشنگ", "homayoon", "homayoun", "homaioon", "homaioun", "هوتن", "homeyra",
     "homeira", "هورداد", "hooman", "human", "houman", "هورمزد", "hooravash", "hourvash", "huravash", "هورموند",
     "hooshang", "houshang", "hushang", "هرمز", "hootan", "hutan", "houtan", "حسین", "hordad", "hourdad", "هومن",
     "hormazd", "hoormazd", "hourmazd", "هوشیار", "hormond", "ایلیا", "hormoz", "ایمان", "hossein", "hoseyn", "hosein",
     "hosseyn", "houman", "hooman", "human", "hoomaan", "humaan", "houmaan", "ایرج", "houshyar", "hooshyar", "hushyar",
     "hooshiar", "hushiar", "houshiar", "ایران بانو", "ilya", "ilia", "ایراندخت", "iman", "ایرمن", "جبار", "iraj",
     "irajh", "جابر", "ایران‌بانو", "iranbanoo", "iran banoo", "جعفر", "ایران‌دخت", "irandokht", "irman",
     "جهان‌بخش", "jabbar", "jabar", "جهاندار", "jaber", "جهانگیر", "jafar", "ja'far", "جهانشاه", "jahan", "جلال",
     "جهانبخش", "jahanbakhsh", "ژاله", "جهان‌دار", "jahandar", "جلیل", "جهان‌گیر", "jahangir", "jahangeer", "جمال",
     "جهان‌شاه", "jahanshah", "جاماسب", "jalal"]) | set(
    ["جمیل", "jaleh", "jhaleh", "jale", "jhale", "جمیله", "jalil", "جمشید", "jamal", "جنان", "jamasb", "jamaseb",
     "جاسم", "jamil", "جواد", "jamileh", "جاوید", "jamshid", "janan", "جیران", "jasem", "ژیلا", "javad",
     "jawad", "ژینا", "javid", "ژینر", "jebran", "jobran", "jabran", "ژوبین", "jeyran", "کژال", "jila", "jhila",
     "کاژاو", "jina", "jhina", "كمال", "jinar", "jhinar", "کمند", "joubin", "jhoobin", "joobin", "jhoubin", "کامبیز",
     "kajal", "kajhal", "کامران", "kajhao", "kajao", "کامشاد", "kamal", "کامیار", "kamand", "کنعان", "kambiz", "کارن",
     "kamran", "کرانه", "کام‌شاد", "kamshad", "کاردو", "کام‌یار", "kamyar", "kamiar", "كریم", "kan'an", "kanan",
     "کاروخ", "karan", "karen", "کارزان", "karane", "karaneh", "کتایون", "kardo", "کاوه", "karim", "کاووس", "karookh",
     "karoukh", "کاظم", "karzan", "کازیوه", "katayun", "katayoun", "katayoon", "کیخسرو", "kaveh", "kawe", "kaweh",
     "kave", "کنارنگ", "kavous", "kavoos", "kawous", "kawoos", "kazem", "kaazem", "کیان", "کازی‌وه", "kazio",
     "kaziveh", "kaaziveh", "کیقباد", "کی‌خسرو", "keikhosro", "keykhosro", "کیکاووس", "kenarang", "کیوان", "keshvar",
     "keshwar", "کیوس", "keyan", "kian", "خلیل", "کی‌قباد", "keyghobad", "keyqobad", "خشایار", "keykavoos", "keykavous",
     "خدابخش", "keyvan", "keivan", "k1", "keywan", "keiwan", "خداداد", "keyvoos", "keivoos", "keyvous", "keivous",
     "خدایار", "khalil", "خجسته", "khashayar", "خناو", "khodabakhsh", "خوبیار", "khodadad", "خورشید", "khodayar",
     "خسرو", "khojasteh", "khojaste", "خوناس", "khonav", "خوروش", "خوب‌یار", "khoobyar", "khubyar", "khoubyar",
     "کیانوش", "khorshid", "کیارش", "khosro", "khosrow", "کیاوش", "khounas", "khoonas", "کیومرث", "khourvash",
     "khoorvash", "كبری", "kianoosh", "kianush", "kianoush", "کوکب", "kiarash", "kyarash", "کوماس", "kiavosh",
     "kiavash", "کیومرس", "kiomars", "kiumars", "qmars", "کوثر", "kobra", "kobraa", "کورس", "kokab", "kowkab", "کورش",
     "koomas", "koumas", "لادن", "kousha", "kusha", "لاله", "kosar", "kowsar", "لاله‌رخ", "kouros", "koros", "kooros",
     "kuros", "لاوچاک", "kourosh", "koorosh", "kurosh", "لیزان", "ladan", "لهراسب", "laleh", "lale", "ماهک", "لاله رخ",
     "lalerokh", "lalehrokh", "ماهان", "laochak", "lawchak", "laowchak", "مهستی", "lizan", "ماه‌برزین", "lohraseb",
     "lohrasb", "مهبد", "mahak", "ماه‌چهر", "mahan", "مهداد", "mahasti", "mahsiti", "mahsati", "مهدی", "mahbarzin",
     "mahbarzyn", "مهدیار", "مه‌بد", "mahbod", "مهدیس", "mahchehr", "maahchehr", "مهدخت", "مه‌داد", "mahdad", "ماهدخت",
     "mahdi", "mehdi", "مهین", "mahdiar", "mahdyar", "ماه‌جهان", "مه‌دیس", "mahdis", "مهکامه"]) | set(
    ["مه‌دخت", "mahdokht", "محمود", "ماه‌دخت", "mahdokht", "maahdokht", "مهناز", "mahin", "مهنوش", "mahjahan",
     "maahjahan", "ماهنوش", "mahkame", "mahkameh", "ماهور", "mahmood", "mahmoud", "mahmud", "ماه‌پری", "مه‌ناز",
     "mahnaz", "مهرخ", "mahnoosh", "mahnoush", "mahnush", "مهسا", "ماه‌نوش", "mahnoush", "mahnoosh", "mahnush",
     "maahnoush", "maahnoosh", "maahnush", "مهشاد", "mahoor", "mahur", "mahour", "maahoor", "maahur", "maahour",
     "مهشید", "mahpari", "مهتا", "مه‌رخ", "mahrokh", "مهتاب", "mahsa", "ماهتو", "mahshad", "مهوش", "mahshid", "مهیار",
     "مه‌تا", "mahta", "ماهزاد", "مه‌تاب", "mahtab", "مهزاد", "ماه‌تو", "mahto", "mahtow", "maahto", "maahtow",
     "مهزیار", "مه‌وش", "mahvash", "مجید", "mahyar", "mahiar", "ماکان", "ماه‌‌زاد", "mahzad", "maahzad", "ملک‌جهان",
     "mahzad", "ملیحه", "mahziar", "mahzyar", "مامک", "majid", "مانا", "makan", "maakan", "ماندان", "malekjahan",
     "ماندانا", "malihe", "maliheh", "مانلی", "mamak", "maamak", "مانشت", "mana", "maana", "منیژه", "mandan", "منوچهر",
     "mandana", "منصور", "manely", "maneli", "manelee", "مارال", "manesht", "مرداویج", "manijeh", "manije", "manijhe",
     "manijheh", "مرجانه", "manouchehr", "manoochehr", "manuchehr", "مرجان", "mansoor", "mansour", "mansur", "مریم",
     "maral", "مرضیه", "mardawich", "mardavich", "مسل", "marjane", "marjhaneh", "معصومه", "marjhan", "marjan", "مستانه",
     "maryam", "mariam", "مزدک", "marzie", "marzieh", "مازیار", "masal", "مازون", "masoume", "masoumeh", "ma'soume",
     "ma'soumeh", "masume", "masumeh", "ma'sume", "ma'sumeh", "مقداد", "masoumh", "masoume", "masoomeh", "masoome",
     "masoome", "masoomeh", "ma'soome", "ma'soomeh", "مهرا", "mastaneh", "mastane", "مهراب", "mazdak", "مهراد",
     "maziar", "mazyar", "مهرک", "mazoun", "mazoon", "mazun", "مهران", "meghdad", "meqdad", "meghdaad", "meqdaad",
     "مهرانه", "مهرنگ", "mehrab", "مهرانگیز", "mehrad", "مهراز", "mehrak", "مهرداد", "mehran", "مهرگان", "mehrane",
     "mehraneh", "مهری", "mehrang", "مه‌ریوان", "mehrangiz", "مهرریز", "mehraz", "مهرسا", "mehrdad", "مهرشاد",
     "mehregan", "mehrgan", "مهروا", "mehri", "mehry", "مهرزاد", "mehrivan", "mehriwan", "ملیسا", "mehrriz", "معراج",
     "mehrsa", "میثم", "mehrshad", "میعاد", "mehrwa", "mehrva", "میگل", "mehrzad", "میخک", "melisa", "میلاد", "meraj",
     "meraaj", "me'raj", "me'raaj", "میلان", "meysam", "meisam", "مینا", "miad", "mi'ad", "meead", "mead", "mee'ad",
     "mea'ad", "مینو", "migel", "meygol", "meigol", "میران", "mikhak", "میترا", "milad", "محدثه", "milan", "محمد",
     "mina", "محسن", "minoo", "minu", "minou", "محترم", "miran", "موژان", "mitra", "مژده", "mohadese", "mohadeseh",
     "mohaddese", "mohaddeseh", "مژگان", "mohamad"]) | set(
    ["mohammad", "مجتبی", "mohsen", "مختار", "mohtaram", "مونا", "mojan", "mojhan", "منور", "mojdeh", "mojde", "mojhde",
     "mojhdeh", "منیر", "mojgan", "mojhgan", "مراد", "mojtaba", "mojtabaa", "مرداس", "mokhtar", "mokhtaar", "مرتضی",
     "mona", "مروارید", "monavar", "monawar", "monavvar", "monawwar", "مسیب", "monir", "مشکان‌دخت", "morad",
     "مشکین‌دخت", "mordas", "mardas", "مسلم", "morteza", "mortezaa", "مصطفا", "morwarid", "morvarid", "morvaryd",
     "morwaryd", "مظفر", "mosayeb", "mosayyeb", "نه‌به‌ز", "moshkandokht", "نچیروان", "moshkindokht", "meshkindokht",
     "نادر", "moslem", "نادیا", "مصطفی", "mostafa", "نعیمه", "mozafar", "mozaffar", "نفیسه", "nabaz", "نقی",
     "nachirvan", "nachirwan", "nachirowan", "نهال", "nader", "naader", "ناهید", "nadia", "ناژیلا", "naeeme", "naeemeh",
     "na'eeme", "na'eemeh", "ناژین", "nafise", "nafiseh", "نکیسا", "naghi", "naqi", "naghee", "naqee", "نامیا", "nahal",
     "نرگس", "nahid", "nahyd", "نریمان", "najila", "najhila", "نرمین", "najin", "najhin", "naajin", "naajhin",
     "نه‌هروز", "nakisa", "ناصر", "namia", "namya", "نه‌وشیروان", "نرجس", "narges", "narjes", "ناسیکو", "nariman",
     "naryman", "نسیم", "narmin", "نسرین", "narouz", "naorouz", "narooz", "naorooz", "naroz", "naoruz", "نسترن",
     "naser", "naaser", "nashirvan", "nashirwan", "nashiravan", "nashirawan", "نوال", "nasiko", "nasyko", "نوید",
     "nasim", "نایب", "nasrin", "نازآفرین", "nastaran", "نازنین", "نازگل", "naval", "navaal", "navid", "نازیلا",
     "nayeb", "naieb", "نازلی", "nazafarin", "نگار", "nazanin", "نگارین", "nazgol", "naazgol", "نگین", "nazi",
     "نعمت‌الله", "nazila", "نسکو", "nazli", "naazli", "نیاسا", "negar", "نیکسا", "negarin", "negin",
     "nematollah", "nematolah", "ne'matolah", "ne'matollah", "نیلوفر", "nesco", "nesko", "نیما", "niasa", "nyasa",
     "نیوشا", "نیک‌سا", "nicsa", "niksa", "نیشا", "niki", "nicky", "nicki", "نوژن", "nikoo", "nickoo", "nickou",
     "nikou", "niku", "nicku", "نوش‌آفرین", "nilufar", "niloofar", "niloufar", "نوشین", "nima", "نوشزاد", "نیوش‌آ",
     "nioosha", "niousha", "niusha", "نرمن", "nisha", "نوذر", "niusha", "niosha", "nojan", "nojhan", "nowjan",
     "nowjhan", "اورنگ", "نوشافرین", "nooshafarin", "noushafarin", "nushafarin", "نوش‌این", "nooshin",
     "noushin", "nushin", "پادینا", "نوش‌زاد", "nooshzad", "noushzad", "nushzad", "پهلبد", "norman", "پائیزه", "nozar",
     "nouzar", "nowzar", "پانیذ", "omid", "پانیز", "orang", "پرند", "padideh", "padide", "پرستو", "padina", "پردیس",
     "pahbod", "پرهام", "paiize", "paeezeh", "پریا", "paniz", "پریچهر", "paniz", "پریدخت", "parand", "پریناز",
     "parastoo", "parastou", "پریرو"]) | set(
    ["pardis", "پریسا", "pardis", "پریشاد", "parham", "پریوش", "paria", "parya", "پریزاد", "پری‌چهر", "parichehr",
     "پارمیدا", "پری‌دخت", "paridokht", "پارمیس", "پری‌ناز", "parinaz", "پرنیا", "پری‌رو", "pariroo", "pariru",
     "پرنیان", "parisa", "پارسا", "پری‌شاد", "parishad", "پرشان", "پری‌وش", "parivash", "pariwash", "پروانه", "پری‌دخت",
     "parizad", "پروین", "parmida", "پرویز", "parmis", "پشنگ", "parnia", "پشوتن", "parnian", "پایا", "parsa", "پیام",
     "parshan", "پدرام", "parvaneh", "parwaneh", "parvane", "parwane", "پگاه", "parvin", "parwin", "پژهان", "parviz",
     "پژمان", "pashang", "پیمان", "pashootan", "pashoutan", "پیران", "paya", "پیروز", "payam", "پیشداد", "pedram",
     "پوپک", "pegah", "پویان", "pejhan", "پولاد", "pejman", "pejhman", "پونه", "peyman", "پوران", "piran", "پوراندخت",
     "pirooz", "pirouz", "پورداد", "pishdad", "پوری", "poopak", "poupak", "پوریا", "pooyan", "pouyan", "puyan", "پویا",
     "poulad", "poolad", "pulad", "رابعه", "pouneh", "pooneh", "puneh", "pune", "poune", "poone", "رادین", "pouran",
     "pooran", "رادمان", "pouran", "pooran", "puran", "پوران‌دخت", "pourandokht", "poorandokht", "purandokht", "رحیم",
     "pourdad", "poordad", "purdad", "رحمان", "pouri", "puri", "poori", "رجب", "pouria", "pooria", "رخشان", "pouria",
     "pooria", "puria", "رامان", "pouya", "pooya", "puya", "رامبد", "rabeeh", "رامین", "radin", "رامینا", "radman",
     "رامتین", "رامیار", "rahim", "rahym", "رانیا", "rahman", "rahmaan", "راشر", "rajab", "رسول", "rakhshan", "رستان",
     "raman", "روان", "rambod", "رایان", "ramin", "رازان", "ramina", "راضیه", "ramtin", "رنین", "ramyar", "ramiar",
     "ریحانه", "ranya", "rania", "رضا", "rasher", "ریونیز", "rasool", "rasoul", "rasul", "رهام", "rastan", "روجا",
     "ravan", "rawan", "روژینا", "rayan", "رخساره", "razan", "رکسانا", "razie", "razieh", "raazie", "raazieh", "رُمیسا",
     "renin", "ranin", "روناک", "reyhaneh", "reihaneh", "reyhane", "reihane", "روشنک", "reza", "رستم", "rioniz",
     "رودابه", "roham", "raham", "روح‌انگیز", "roja", "روزبه", "rojina", "rojhina", "رویا", "rokhsare", "rokhsareh",
     "رزیتا", "roksana", "صبا", "رمیسا", "romisa", "صابر", "ronak", "صادق", "roshanak", "ساعد", "rostam", "سعید",
     "roudabeh", "roodabeh", "صفر", "روحانگیز", "rouhangiz", "roohangiz", "ساغر", "rouzbeh", "roozbeh", "ساقی", "roya",
     "سهام", "rozita", "سهند", "saba", "سحر", "saber", "saaber", "سهبا", "sadegh", "saadegh", "sadeq", "saadeq", "شبره",
     "saed", "saaed", "sa'ed", "saa'ed", "سجاد", "saeed", "sa'eed", "سالار", "safar", "صالح", "saghar", "saqar",
     "سالم"]) | set(
    ["saghi", "saqi", "سلمان", "saham", "sahaam", "soham", "sohaam", "سامان", "sahand", "سمانه", "sahar", "سامیه",
     "sahba", "سمین", "شب‌ره", "sahbrah", "سمیر", "sajad", "sajjad", "سمیرا", "salar", "ساناز", "saleh", "saaleh",
     "سارا", "salem", "saalem", "سارک", "salman", "سرگل", "saman", "سارینا", "samaneh", "samane", "سروناز", "samie",
     "samieh", "saamie", "saamieh", "ساسان", "ثمین", "samin", "ستار", "samira", "صدیقه", "samira", "سپنتا", "sanaz",
     "سپهر", "sara", "سپیده", "sarak", "ستاره", "sargol", "سودا", "sarina", "سیف‌الله", "sarvenaz", "sarvnaz", "شعله",
     "sasan", "شباهنگ", "satar", "sattar", "شعبان", "sedighe", "sedigheh", "seddighe", "seddigheh", "شبنم", "sepanta",
     "شادان", "sepehr", "شادمهر", "sepideh", "sepide", "شهاب", "setareh", "setare", "شهبال", "sevda", "soda", "sowda",
     "sewda", "شهبد", "seyfollah", "seifollah", "seyfolah", "seifolah", "شاهین", "sha'ban", "شهین", "shabahang", "شهیر",
     "shaban", "شه‌مال", "shabnam", "شه‌مزین", "shadan", "شهنام", "shadmehr", "شهناز", "shahab", "شاهو", "شه‌بال",
     "shahbal", "شهپر", "shahbod", "شهراد", "shahin", "شهرام", "shahin", "شهربانو", "shahir", "شهرداد", "شه مال",
     "shahmal", "شهریار", "شه مزین", "shahmazin", "شهرناز", "shahnam", "شهرخ", "shahnaz", "شاهرخ", "shahou", "shahoo",
     "shahu", "شهروز", "shahpar", "شهرزاد", "shahrad", "شهیار", "shahram", "shahrum", "شاهکام", "shahrbanoo",
     "shahrbanou", "shahrbanu", "شکیبا", "shahrdad", "شانار", "shahriar", "shahryar", "شاپرک", "shahrnaz", "شاپور",
     "شه‌رخ", "shahrokh", "shahroq", "شایا", "شاه‌رخ", "shahrokh", "شایان", "shahrooz", "شروین", "shahrzad", "شیدا",
     "shahyar", "shahiar", "شیده", "شاه‌کام", "shakam", "shahkam", "شیما", "shakiba", "شیرنگ", "shanar",
     "shaparak", "شیرین‌بانو", "shapoor", "shapour", "شیریزدان", "shaya", "shaia", "شیرکو", "shayan", "shaian",
     "شیروان", "shervin", "sherwin", "شیرزاد", "sheyda", "sheida", "شیوا", "shide", "shideh", "شعیب", "shima", "شهره",
     "shirang", "شوکا", "shirin", "شوپه", "shirin banou", "shirinbanoo", "شوآن", "shirizdan", "سیامک", "shirkoo",
     "shirku", "سیاوش", "shirkou", "shirkoo", "سیما", "shirvan", "سیمین", "shirzad", "سینا", "shiva", "shiwa", "سیروس",
     "shoayb", "shoaib", "صغری", "shohreh", "shohre", "سوگل", "shooka", "shouka", "سهی", "shoope", "shoopeh", "shoupeh",
     "shupeh", "shoupe", "shupe", "سهیلا", "شووان", "showan", "shouvan", "سهیل", "siamak", "سهراب", "siavash",
     "syavash", "سلماز", "sima", "سوده", "simin", "سوسن", "sina", "سوزان", "sirous", "siroos", "سُرنا", "soghra",
     "soghraa", "سرور", "sogol", "سروش", "sogol", "ثریا", "soha"]) | set(
    ["sohaa", "سوشیانت", "soheila", "soheyla", "سوشیانس", "soheyl", "soheil", "سودابه", "sohrab", "سورن", "solmaz",
     "سورنا", "soode", "soodeh", "soosan", "sousan", "soozan", "souzan", "suzan", "تقی", "سرنا", "sorena", "طاها",
     "soroor", "sorour", "sarvar", "sorur", "تهمتن", "soroush", "soroosh", "sorush", "طاهره", "sorya", "تهماسب",
     "soshianet", "soshiant", "تهمینه", "soshians", "تهمورث", "soudabeh", "soodabeh", "ته‌نیا", "souren", "sooren",
     "طناز", "sourena", "soorena", "ترنم", "ترسا", "تیروژ", "taghi", "ترمه", "taha", "تینا", "tahamtan", "تیرداد",
     "tahereh", "tahere", "تیریژ", "tahmasb", "tahmaseb", "تونیا", "tahmineh", "tahmine", "تراب", "tahmoures",
     "tahmoores", "ترنگ", "tahnia", "tahnya", "تورج", "tanaz", "tannaz", "توران", "taranom", "tarannom", "توراندخت",
     "tarsa", "اورمزد", "teerooj", "tirouj", "وحید", "termeh", "terme", "وهومن", "tina", "ولی‌الله", "tirdad", "ونداد",
     "tirij", "tirijh", "وندیداد", "tonia", "tonya", "وریا", "torab", "ویس", "ترنج", "torang", "toranj", "یاس",
     "touraj", "tooraj", "touran", "tooran", "توران‌دخت", "tourandokht", "toorandokht", "یاسمن", "urmazd",
     "oormazd", "یاسمین", "vahid", "یاسر", "vahooman", "vahuman", "vahouman", "یاسین", "valiolah", "valiollah", "یسنا",
     "vandad", "wandad", "یاور", "vandidad", "wandidad", "یزدان", "varia", "varya", "verya", "veria", "یزدگرد", "veys",
     "vase", "vaise", "veis", "vais", "یگانه", "yaas", "yas", "یوتاب", "yadegar", "یونس", "یارآ", "زال", "yasaman",
     "زاب", "yaseen", "yasin", "yasean", "زهور", "yaser", "زهرا", "yasin", "yasean", "yaseen", "زامیاد", "yasna",
     "yasna", "yavar", "زانیار", "yazdan", "زری", "yazdgerd", "زرین", "yegane", "yeganeh", "زرین‌دخت", "یوت‌آب",
     "yootab", "youtab", "utab", "زرمهر", "younes", "yoones", "yunes", "‍‍‍‍‍زاوش", "zaal", "زایه‌له", "زینب", "zahoor",
     "zahur", "zahour", "زینا", "zahra", "زینت", "zamyad", "zamiad", "زیور", "zand", "زهره", "zanyar", "zaniar",
     "زوبین", "zari", "زویا", "zarin", "zarrin", "اميرحسين", "zarindokht", "zarrindokht", "محمدامين", "zarmehr", "كيان",
     "zavash", "kian", "kyan", "محمدپارسا", "zayeleh", "zayele", "مهدي", "zeinab", "zeynab", "اميرعلي", "امیر‌علی",
     "zina", "آرتين", "zinat", "artin", "aartin", "اميرمحمد", "zivar", "ziwar", "محمدمتین", "zohreh", "zohre", "matin",
     "محمدطاها", "zoobin", "zubin", "taahaa", "taha", "tahaa", "taaha", "دانیال", "zoya", "danial", "danyal", "daanial",
     "daanyal", "محمدمهدی", "گل بهار", "نيما", "nima", "nimaa", "سام", "sam", "saam", "عرشيا", "arshia", "arshya",
     "arshiaa", "arshyaa", "عرفان"]) | set(
    ["erfan", "erfaan", "آرسین", "arsin", "arsyn", "aarsin", "aarsyn", "مانی", "mani", "maani", "ابوالفضل", "abolfazl",
     "abalfazl", "سبحان", "sobhan", "sobhaan", "محمدحسين", "محمدياسين", "مبين", "mobin", "کوروش", "koorosh", "kourosh",
     "kurosh", "محمدرضا", "reza", "rezaa", "علی رضا", "يوسف", "yousef", "yoosef", "yusef", "yousof", "yoosof", "yusof",
     "آبتین", "abtin", "aabtin", "ياسين", "yasin", "yaasin", "مهرسام", "mehrsam", "mehrsaam", "آدرین", "adrin",
     "aadrin", "باراد", "barad", "baraad", "مصطفی", "mostafa", "اميرعباس", "abbas", "abas", "علی اکبر", "اميررضا",
     "رادوین", "radvin", "radwin", "raadvin", "raadwin", "متين", "matin", "آرمیا", "اِرمیا", "armia", "armya", "aarmia",
     "aarmya", "ermia", "ermya", "محمدجواد", "javad", "jawad", "javaad", "jawaad", "اميرمهدي", "هیراد", "hirad",
     "hyrad", "hiraad", "hyraad", "علی اصغر", "حمیدرضا", "محمدعلی", "احمدرضا", "اميرحافظ", "hafez", "haafez", "ارمیا",
     "آئیل", "aeel", "a'eel", "aayil", "ayil", "ayeel", "aayeel", "محیا", "mahya", "mahia", "mahyaa", "mahiaa", "النا",
     "elena", "elenaa", "هلیا", "helia", "helya", "heliaa", "helyaa", "الینا", "elina", "elinaa", "elyna", "elynaa",
     "آنیتا", "anita", "anyta", "anitaa", "anytaa", "مرسانا", "mersana", "mersanaa", "آوینا", "avina", "aavina", "avinaa", "aavinaa", "awina", "aawina", "awinaa", "aawinaa", "آیلین", "aylin",
     "aaylin", "ailin", "aailin", "aylyn", "aaylyn", "ailyn", "aailyn", "کیمیا", "kimia", "kymya", "kymia", "kimya", "kimiaa", "kymyaa", "kymiaa", "kimyaa", "رونیکا", "ronika", "ronica", "درسا",
     "dorsa", "dorsaa", "ثنا", "sena", "senaa", "تارا", "tara", "taara", "آدرینا", "aadrina", "adrina", "aadryna",
     "adryna", "یلدا", "yalda", "yaldaa", "فاطمه زهرا", "آیناز", "aynaz", "aaynaz", "ainaz", "aainaz", "غزل", "ghazal",
     "qazal", "کیانا", "kiana", "kyana", "ملینا", "melina", "melyna", "آرشیدا", "arshida", "aarshida", "arshyda",
     "aarshyda", "هانا", "hanaa", "hana", "haana", "haanaa", "آنیا", "aania", "aanya", "ania", "anya", "پریماه",
     "parimah", "parymah", "فاطیما", "fatima", "faatima", "fatyma", "faatyma", "fatimaa", "faatimaa", "fatymaa",
     "faatymaa", "آرنیکا", "arnika", "arnica", "aarnika", "aarnica", "سلنا", "selena", "selenaa", "نازنین زهرا",
     "آترینا", "atrina", "aatrina", "atryna", "aatryna", "وانیا", "vania", "vanya", "wania", "wanya", "سوگند", "sogand",
     "sowgand"]) | set(["حدیثه", "hadise", "hadiseh"])


def get_real_names(s):
    # __force_utf8_encoding_to_get_this_to_work__
    # the utf-8 encoding at the start of this file lets us add persian characters, however that encoding differs from
    # the unicode encoding (even tho the string is utf-8 encoded, but python style :D)
    s = s.encode("utf-8")
    return list(
        set(
            [
                word.strip(string.punctuation)
                for word
                in s.replace('<', ' ').replace('>', ' ').replace('.', ' ').lower().split()
                ]
        )
        & names)


class WithRealnameDetection(object):
    def __init__(self, *args, **kwargs):
        super(WithRealnameDetection, self).__init__(*args, **kwargs)
        self.real_names = []

    def clean(self, *args, **kwargs):
        cleaned_data = super(WithRealnameDetection, self).clean(*args, **kwargs)
        message = cleaned_data.get('message', '') + cleaned_data.get('title', '')
        if message:
            real_names = list(get_real_names(message))
            self.real_names = real_names
        return cleaned_data

    def save(self, *args, **kwargs):
        instance = super(WithRealnameDetection, self).save(*args, **kwargs)
        if len(self.real_names):
            self.add_disapproval_reason('Possible real names found: {0}'.format(", ".join(self.real_names)))  # Do not translate
        return instance
